//! Cross-entity bridges that let one `#[expose]` macro emit a field resolver
//! pointing at another entity's loader **without knowing its service name**.
//!
//! Each `#[expose]` emits an impl of [`PkLoadable`] on its entity (Phase 1)
//! and, when relevant, of [`RelatedTo<Parent>`] (Phase 2 / `HasMany`). A field
//! resolver on the `belongs_to` side only needs the target entity's path —
//! the loader struct it must pull from the request context is reached via
//! `<TargetEntity as PkLoadable>::Loader`, and the GraphQL output type via
//! `<TargetEntity as PkLoadable>::Wire`.

use async_graphql::OutputType;
use async_graphql::connection::{Connection, Edge};

/// The dataloader key for **one parent's page** of an auto-resolved `has_many`.
///
/// A relation field that paginates cannot batch on the parent key alone: two
/// sibling selections may ask for different windows of the same relation, and a
/// loader keyed only by parent would serve whichever arrived first to both. The
/// window travels in the key, so a batch groups by `(first, after)` and pages
/// every parent in that group together.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct RelationKey<K> {
    /// The parent row's primary key — the child's foreign-key value.
    pub parent: K,
    /// Page size, already clamped by `nest_rs_seaorm::clamp_page_size`.
    pub first: u64,
    /// Exclusive cursor: the last child key of the previous page.
    pub after: Option<uuid::Uuid>,
}

/// One parent's page of children, as the loader hands it back: each child
/// beside the cursor addressing it, plus whether a further page exists.
///
/// Not an `async_graphql::connection::Connection` — a `Loader::Value` must be
/// `Clone` and a `Connection` is not. The cursor is computed here rather than in
/// the field resolver because only the *child's* macro knows which column is its
/// primary key; by the time the parent's resolver sees the row it is an opaque
/// `RelatedTo::Wire`.
#[derive(Clone, Debug)]
pub struct RelationPage<T> {
    /// `(cursor, node)` in primary-key order.
    pub edges: Vec<(String, T)>,
    /// Whether a further page exists — an over-fetched row, not a count.
    pub has_next_page: bool,
}

impl<T> Default for RelationPage<T> {
    /// The empty page a parent with no children resolves to. Reached through
    /// `load_one(..).unwrap_or_default()`, which is why it cannot derive
    /// (`T` need not be `Default`).
    fn default() -> Self {
        Self {
            edges: Vec::new(),
            has_next_page: false,
        }
    }
}

impl<T: OutputType> RelationPage<T> {
    /// The Relay connection this page ships as.
    ///
    /// `has_previous_page` is the caller's to state: it is `after.is_some()`,
    /// which the resolver knows and the page does not.
    pub fn into_connection(self, has_previous_page: bool) -> Connection<String, T> {
        let mut connection = Connection::new(has_previous_page, self.has_next_page);
        connection.edges.extend(
            self.edges
                .into_iter()
                .map(|(cursor, node)| Edge::new(cursor, node)),
        );
        connection
    }
}

/// "This entity exposes a primary-key loader and a wire DTO." Implemented
/// automatically by `#[expose]` on every entity that declares a `service = …`.
///
/// - `Loader` is the struct generated by `#[dataloader]` on the entity's
///   `by_id` method — typically named `<Service>ById`.
/// - `Wire` is the GraphQL output type emitted by `#[expose(name = "…")]`.
pub trait PkLoadable {
    /// The `#[dataloader]`-generated primary-key loader (`<Service>ById`).
    type Loader: ::core::marker::Send + ::core::marker::Sync + 'static;
    /// The GraphQL output type `#[expose(name = "…")]` emits for this entity.
    type Wire: OutputType + ::core::marker::Send + ::core::marker::Sync + 'static;
}

/// The `Via` a `HasMany` takes when it names no column: "the one foreign key
/// this child has to that parent".
///
/// A child declaring **two** `belongs_to` at one parent has no such column, so
/// `#[expose]` emits no `RelatedTo<Parent, SoleForeignKey>` for it at all — the
/// parent must then say which key the relation follows, with
/// `#[expose(via = "…")]`. That absence is the whole enforcement: the ambiguous
/// case is a compile error at the relation that is ambiguous, never a silent
/// pick of whichever `belongs_to` was declared first.
pub struct SoleForeignKey;

/// "This entity is the child of `Parent`, fetched in batches by its
/// foreign-key column." Phase 2 — populated by `#[expose]` on the entity
/// owning the FK.
///
/// `Via` names *which* foreign key, and exists because the parent's side of the
/// relation has nothing else to name it with: it knows the child's entity type
/// and a column name the developer wrote, and a column name is not a type.
/// `#[expose]` therefore emits one zero-sized marker per `belongs_to` beside
/// the child's entity — `By<PascalColumn>` — plus a
/// [`SoleForeignKey`] impl when the child points at that parent exactly once.
/// The developer names the column, never the marker.
#[diagnostic::on_unimplemented(
    message = "`{Self}` is not reachable as a `has_many` child of `{Parent}` through `{Via}`",
    label = "no foreign key selected",
    note = "an auto-resolved `has_many` reaches its children through the child's own `#[sea_orm(belongs_to, from = \"…\")]`",
    note = "two `belongs_to` columns pointing at one parent leave no default — name the one this relation follows with `#[expose(via = \"<fk_column>\")]` on the `HasMany` field"
)]
pub trait RelatedTo<Parent: ?Sized, Via: ?Sized = SoleForeignKey> {
    /// The FK loader that batches this child by its foreign-key column.
    type Loader: ::core::marker::Send + ::core::marker::Sync + 'static;
    /// The GraphQL output type for this child entity.
    type Wire: OutputType + ::core::marker::Send + ::core::marker::Sync + 'static;
}
