pub const STANDALONE_CARGO: &str = r#"[package]
name = "{{kebab}}"
version = "0.1.0"
edition = "2024"
rust-version = "1.95"

[dependencies]
anyhow = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
nest-rs-core = "0.1"
nest-rs-http = "0.1"
poem = { version = "3", features = ["tower-compat", "anyhow", "rustls"] }

[dev-dependencies]
nest-rs-testing = "0.1"
"#;

pub const WORKSPACE_CARGO: &str = r#"[package]
name = "{{kebab}}"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
nest-rs-core.workspace = true
nest-rs-guards.workspace = true
nest-rs-http.workspace = true
nest-rs-interceptors.workspace = true
poem.workspace = true
tokio.workspace = true
anyhow.workspace = true

[dev-dependencies]
nest-rs-testing.workspace = true

[lints]
workspace = true
"#;

pub const MAIN: &str = r#"use anyhow::Result;
use nest_rs_core::App;

use {{kebab}}::{{module}};

#[tokio::main]
async fn main() -> Result<()> {
    App::builder()
        .module::<{{module}}>()
        .build()
        .await?
        .run()
        .await
}
"#;

pub const STANDALONE_MAIN: &str = r#"use anyhow::Result;
use nest_rs_core::App;

mod controller;
mod module;
mod service;

use module::{{module}};

#[tokio::main]
async fn main() -> Result<()> {
    App::builder()
        .module::<{{module}}>()
        .build()
        .await?
        .run()
        .await
}
"#;

pub const LIB: &str = r#"mod controller;
mod module;
mod service;

pub use module::{{module}};
"#;

pub const MODULE_HELLO: &str = r#"use nest_rs_core::module;
use nest_rs_http::HttpModule;

use crate::controller::{{controller}};
use crate::service::{{service}};

#[module(
    imports = [HttpModule::for_root(None)],
    providers = [{{service}}, {{controller}}],
)]
pub struct {{module}};
"#;

pub const MODULE_EMPTY: &str = r#"use nest_rs_core::module;
use nest_rs_http::HttpModule;

#[module(imports = [HttpModule::for_root(None)])]
pub struct {{module}};
"#;

pub const SERVICE: &str = r#"use nest_rs_core::injectable;

#[injectable]
#[derive(Default)]
pub struct {{service}};

impl {{service}} {
    pub fn greeting(&self) -> String {
        "Hello World".to_string()
    }
}
"#;

pub const CONTROLLER: &str = r#"use std::sync::Arc;

use nest_rs_http::{controller, routes};

use crate::service::{{service}};

#[controller(path = "/")]
pub struct {{controller}} {
    #[inject]
    svc: Arc<{{service}}>,
}

#[routes]
impl {{controller}} {
    #[get("/")]
    async fn hello(&self) -> String {
        self.svc.greeting()
    }
}
"#;

pub const E2E: &str = r#"use {{kebab}}::{{module}};
use nest_rs_testing::TestApp;

#[tokio::test]
async fn hello_endpoint_greets() {
    let app = TestApp::for_module::<{{module}}>()
        .await
        .expect("{{module}} boots and mounts its routes");

    let resp = app.http().get("/").send().await;
    resp.assert_status_is_ok();
    resp.assert_text("Hello World").await;
}
"#;

pub const GITIGNORE: &str = r#"/target
.env.local
"#;

pub const README: &str = r#"# {{kebab}}

NestRS application generated by `nestrs new`.

```bash
cargo run
curl http://localhost:3000/
```
"#;
