//! The canon join: every fact about the framework that a docs page is checked
//! against, derived here and published as `docs/canon.json`.
//!
//! **Why a file, and why that path.** The docs linter used to derive these facts
//! itself — seven readers under `docs/scripts/lint-docs.mjs` opening
//! `crates/**`, `demo/**` and the root manifest, and re-deriving in JavaScript,
//! with regexes, what this crate derives in Rust with `syn` and `toml_edit`. Two
//! implementations of one definition is the defect
//! `.claude/rules/testing.md` names in clause 1, and it shipped: the linter
//! counted 27 umbrella capabilities where the umbrella join counted 28, while
//! its own comment claimed the two derivations could not disagree.
//!
//! Three properties follow from publishing the facts instead, and each was a
//! separate defect before:
//!
//! - **One derivation.** The linter reads this file and never re-derives. There
//!   is no second reader of the framework's source, so there is nothing to
//!   drift — mechanically, not by discipline.
//! - **A true trigger.** `docs-pages.yml` filters on `docs/**`, and the linter's
//!   input set is now exactly that. Before, the job declared one input class of
//!   eight; a framework change that falsified a page did not run it, and the
//!   failure surfaced later on an unrelated docs commit, naming a page nobody
//!   had touched.
//! - **The right commit.** A `crates/` change that moves a fact regenerates this
//!   file, so the commit that breaks a page is also the commit that touches
//!   `docs/**` — and the gate fires there, with the diff that caused it on
//!   screen.
//!
//! **What travels, and in which of two shapes.** The rule is the shared-grammar
//! one: a fact whose comparison needs no grammar travels **extracted** (a list
//! of decorator names, checked with `includes`); a fact whose comparison applies
//! the *same* extractor to both sides travels **raw**, so that extractor stays
//! single and stays on the linter's side. `architecture` is the only member of
//! the second kind — this join slices the document into the two regions the
//! check reads and extracts no token from either, because what a role token *is*
//! must have one definition and the page side cannot move here.
//!
//! **Staleness is this join's business, not the linter's.** The suite asserts
//! the published file equals what the tree derives, so the *Definition of done*
//! is what keeps it current — the same trust every other join in this crate is
//! run under. The linter never checks: verifying would mean reading `crates/`,
//! which is the property this whole seam exists to remove.
//!
//! No baseline. A baseline records cells a join found empty on the day it
//! landed, and this join has no cells — it derives a value and asserts a file
//! equals it. There is nothing to tolerate: the file is right or it is rewritten.

use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::Path;

use nest_rs_conformance::baseline;
use nest_rs_conformance::sources::{
    crate_dirs, exported_decorators, files_with_extension, parsed, read, relative, repo_root,
    rust_files, umbrella_matrix,
};
use serde::Serialize;
use syn::visit::Visit;
use syn::{ItemFn, ItemTrait, TraitItem};

/// Where the published facts live.
///
/// Under `docs/` because the consumer owns a generated artifact here — the same
/// placement `CLAUDE.md` already sanctions for the GraphQL SDL, which an app
/// commits and the dev run regenerates. It is also what makes the trigger true:
/// a framework change that moves a fact lands a `docs/**` diff.
const PUBLISHED: &str = "docs/canon.json";

/// The demo sources a docs fence can quote, published beside the canon.
///
/// **Two files, one derivation, and the split is about the diff.** The facts are
/// twenty-odd values a reviewer reads at a glance; the quoted corpus is 400 KB
/// that churns whenever anything under `demo/` moves. In one file the second
/// drowns the first, and a capability quietly leaving the matrix would land in
/// the middle of a thousand changed lines.
const PUBLISHED_SOURCES: &str = "docs/demo-sources.json";

/// The header the file carries, so a reader who opens it knows what it is and
/// what to run. Generated files get edited by hand exactly once — the time
/// nobody told the editor not to.
const PREAMBLE: &str = "Generated by `cargo nextest run -p nest-rs-conformance`. \
     Never edit by hand: the canon join rewrites it from the tree and fails.";

/// Floors, so a scan reading the wrong tree cannot publish an empty canon that
/// every page then agrees with. Each is comfortably below today's count and
/// names its own population.
mod floors {
    pub const CAPABILITIES: usize = 20;
    pub const DECORATORS: usize = 20;
    pub const LAYER_SUBTRAITS: usize = 4;
    pub const TRAITS: usize = 50;
    pub const TESTS: usize = 1_500;
    pub const CONFIGS: usize = 12;
    pub const ENVELOPE_KEYS: usize = 4;
    pub const DEMO_FILES: usize = 50;
    pub const ROLE_ROWS: usize = 20;
}

/// A `#[config]` struct, as the page publishing its key table has to describe
/// it.
#[derive(Serialize, PartialEq, Eq)]
struct ConfigFacts {
    /// The repo-relative file that declares it, for a message a reader can open.
    source: String,
    /// Field names in declaration order — the keys a table claiming to be
    /// exhaustive owes a row each.
    fields: Vec<String>,
    /// Whether `defaults()` branches on the profile. `/storage/` published the
    /// dev branch of a profile-split default as *the* default, which is the
    /// second thing that page got wrong.
    profile_split: bool,
}

/// A demo source file, as a fence quoting it has to agree with.
///
/// **The lines travel, and that is a deliberate cost.** They are what makes a
/// fence titled with a real file checkable at all: 110 of the 144 such fences
/// were neither byte-for-byte nor marked `(abridged)`, which is what let a page
/// publish a `#[module]` inside a file titled `mod.rs` and a `#[tokio::test]`
/// inside one titled `tests/e2e/main.rs` — both forbidden by rules the framework
/// itself generates into every scaffolded project.
///
/// Carrying them here rather than letting the linter open `demo/` keeps its
/// input set at `docs/**`, so the check fires at both moments that matter: on
/// the page edit, through the docs gate, and on the demo edit, because
/// regenerating this file lands a `docs/**` diff.
#[derive(Serialize, PartialEq, Eq)]
struct DemoFile {
    /// The `port:` it pins, if any — a fence showing a different one contradicts
    /// the app it claims to be quoting.
    port: Option<u32>,
    /// Its lines, trimmed, blanks dropped. Trimmed because an excerpt is
    /// routinely re-indented out of its `impl` block and that is not the claim
    /// being checked; blanks dropped because their placement is the excerpt's.
    lines: Vec<String>,
}

/// The two regions of the architecture rules a page restates, sliced and not
/// extracted — see the module doc on why this one travels raw.
#[derive(Serialize, PartialEq, Eq)]
struct ArchitectureFacts {
    /// Every table row of the rules file, verbatim.
    role_rows: Vec<String>,
    /// The fenced block listing the words a module may not be named after.
    reserved_block: String,
}

/// Everything a docs page can be checked against.
#[derive(Serialize, PartialEq, Eq)]
struct Canon {
    #[serde(rename = "$generated")]
    generated: &'static str,
    /// Every capability a developer can name in `--features`. The landing counts
    /// these; `sources::UmbrellaMatrix` argues why it is features and not crates.
    capabilities: Vec<String>,
    /// Every `#[proc_macro_attribute]` the framework exports.
    decorators: Vec<String>,
    /// Every `pub trait X: Layer` — the Layer System's members.
    layer_subtraits: Vec<String>,
    /// Every `pub trait` the framework ships, mapped to the methods it declares,
    /// so a page publishing a signature can be diffed against the real one.
    trait_methods: BTreeMap<String, Vec<String>>,
    /// The landing's `N+ tests` floor.
    test_count: usize,
    /// `major.minor` of the framework the repo builds — what every documented
    /// `nest-rs*` pin has to say.
    version_req: String,
    /// The binding `nest-rs-opentelemetry`'s boot panic tells a reader to write.
    otel_binding: String,
    /// The keys `nest_rs_queue::envelope` seals onto the wire.
    envelope_keys: Vec<String>,
    /// Every `#[config]` struct, keyed by type name.
    configs: BTreeMap<String, ConfigFacts>,
    architecture: ArchitectureFacts,
}

#[test]
fn the_published_canon_is_what_the_tree_derives() {
    let root = repo_root();
    publish(&root, PUBLISHED, &derive(&root));
}

#[test]
fn the_published_demo_sources_are_what_the_tree_holds() {
    let root = repo_root();
    let sources = demo_files(&root);
    baseline::floor(sources.len(), floors::DEMO_FILES, "demo source files");
    publish(&root, PUBLISHED_SOURCES, &sources);
}

/// Write one artefact and fail, or return because it already matched.
fn publish<T: Serialize>(root: &Path, rel: &str, value: &T) {
    let mut rendered =
        serde_json::to_string_pretty(value).expect("a published artefact is plain data");
    rendered.push('\n');

    let path = root.join(rel);
    if fs::read_to_string(&path).is_ok_and(|current| current == rendered) {
        return;
    }
    fs::write(&path, &rendered).expect("the published artefact is writable");
    panic!(
        "{rel} did not match the tree and has been rewritten — commit it.\n\n\
         It is what the docs linter reads instead of deriving these facts itself, \
         so a framework change that moves one of them lands here too. That is \
         deliberate: it is the diff that makes the docs job fire on the commit \
         that caused it."
    );
}

/// Read every fact, with a floor on each population.
fn derive(root: &Path) -> Canon {
    let matrix = umbrella_matrix(root);
    let capabilities = matrix.features();
    baseline::floor(
        capabilities.len(),
        floors::CAPABILITIES,
        "umbrella capabilities",
    );

    let rust = rust_facts(root);
    baseline::floor(rust.decorators.len(), floors::DECORATORS, "decorators");
    baseline::floor(
        rust.layer_subtraits.len(),
        floors::LAYER_SUBTRAITS,
        "`pub trait _: Layer` declarations",
    );
    baseline::floor(rust.trait_methods.len(), floors::TRAITS, "`pub trait`s");
    baseline::floor(rust.tests, floors::TESTS, "test functions");
    baseline::floor(rust.configs.len(), floors::CONFIGS, "`#[config]` structs");

    let envelope_keys = envelope_keys(root);
    baseline::floor(
        envelope_keys.len(),
        floors::ENVELOPE_KEYS,
        "queue envelope keys",
    );

    let architecture = architecture(root);
    baseline::floor(
        architecture.role_rows.len(),
        floors::ROLE_ROWS,
        "architecture table rows",
    );
    assert!(
        !architecture.reserved_block.is_empty(),
        "no reserved-vocabulary block in the architecture rules — teach `architecture` \
         where it moved, do not publish an empty one",
    );

    Canon {
        generated: PREAMBLE,
        capabilities,
        decorators: rust.decorators,
        layer_subtraits: rust.layer_subtraits,
        trait_methods: rust.trait_methods,
        test_count: rust.tests,
        version_req: version_req(root),
        otel_binding: otel_binding(root),
        envelope_keys,
        configs: rust.configs,
        architecture,
    }
}

/// What one walk of `crates/` yields. One traversal, five facts — the linter's
/// own reason for walking once, kept.
#[derive(Default)]
struct RustFacts {
    decorators: Vec<String>,
    layer_subtraits: Vec<String>,
    trait_methods: BTreeMap<String, Vec<String>>,
    tests: usize,
    configs: BTreeMap<String, ConfigFacts>,
}

fn rust_facts(root: &Path) -> RustFacts {
    let mut out = RustFacts::default();
    let mut decorators = BTreeSet::new();
    let mut subtraits = BTreeSet::new();
    let mut methods: BTreeMap<String, BTreeSet<String>> = BTreeMap::new();

    for dir in crate_dirs() {
        if !dir.starts_with(root.join("crates")) {
            continue;
        }
        decorators.extend(exported_decorators(&dir));
    }

    for file in rust_files(&root.join("crates")) {
        let Some(ast) = parsed(&file) else {
            continue;
        };
        let rel = relative(&file, root);
        let mut scan = FileScan::default();
        scan.visit_file(&ast);
        out.tests += scan.tests;

        // **Declarations come from `src/` only; the test count comes from
        // everywhere.** The two populations differ because the questions do: a
        // page is checked against what the framework *ships*, and a suite
        // fixture is not shipped — `crates/nest-rs-config`'s own tests declare
        // eleven `#[config]` structs named `Owner`, `Reader`, `Sibling`, and
        // publishing those as framework configs would let a page cite one.
        // Tests, by contrast, are counted precisely because they are tests.
        if rel.contains("/tests/") {
            continue;
        }
        subtraits.extend(scan.layer_subtraits);
        // A trait split across crates (a feature-gated half) contributes its own
        // names rather than replacing the set.
        for (name, fns) in scan.trait_methods {
            methods.entry(name).or_default().extend(fns);
        }
        for config in scan.configs {
            out.configs.insert(
                config.name,
                ConfigFacts {
                    source: rel.clone(),
                    fields: config.fields,
                    profile_split: config.profile_split,
                },
            );
        }
    }

    out.decorators = decorators.into_iter().collect();
    out.layer_subtraits = subtraits.into_iter().collect();
    out.trait_methods = methods
        .into_iter()
        .map(|(name, fns)| (name, fns.into_iter().collect()))
        .collect();
    out
}

/// A `#[config]` struct as one file declares it, before its source is known.
///
/// The namespace is what *recognises* one — a struct without it is an ordinary
/// struct — but it does not travel: the linter never builds an env name, and the
/// `docs` join derives namespaces from the source itself. A field no reader
/// consumes is the mirror of a span field nothing records.
struct ConfigDecl {
    name: String,
    fields: Vec<String>,
    profile_split: bool,
}

/// One file's contribution, gathered in a single `syn` walk.
///
/// **A test is any function carrying an attribute whose last path segment is
/// `test`.** That is `sources::TestFns`' definition and it is the considered
/// one: a list of spellings is a hand-maintained set that fails in the unsafe
/// direction the day a runner adds one. The linter counted three literal
/// spellings, one of which (`#[rstest]`) the repo does not use — the two agreed
/// at 2 051 by luck, not by construction.
#[derive(Default)]
struct FileScan {
    tests: usize,
    layer_subtraits: Vec<String>,
    trait_methods: Vec<(String, Vec<String>)>,
    configs: Vec<ConfigDecl>,
    /// Depth inside a `#[cfg(test)]` item — the in-file half of the `/tests/`
    /// skip, since a fixture is as often a `mod tests` beside the code as a
    /// file of its own.
    under_cfg_test: usize,
}

impl FileScan {
    /// Whether a declaration reached now is shipped, or a fixture.
    fn ships(&self) -> bool {
        self.under_cfg_test == 0
    }
}

impl<'ast> Visit<'ast> for FileScan {
    fn visit_item_mod(&mut self, node: &'ast syn::ItemMod) {
        let fixture = nest_rs_conformance::sources::is_cfg_test(&node.attrs);
        self.under_cfg_test += usize::from(fixture);
        syn::visit::visit_item_mod(self, node);
        self.under_cfg_test -= usize::from(fixture);
    }

    fn visit_item_fn(&mut self, node: &'ast ItemFn) {
        if node.attrs.iter().any(|attr| {
            attr.path()
                .segments
                .last()
                .is_some_and(|s| s.ident == "test")
        }) {
            self.tests += 1;
        }
        syn::visit::visit_item_fn(self, node);
    }

    fn visit_impl_item_fn(&mut self, node: &'ast syn::ImplItemFn) {
        if node.attrs.iter().any(|attr| {
            attr.path()
                .segments
                .last()
                .is_some_and(|s| s.ident == "test")
        }) {
            self.tests += 1;
        }
        syn::visit::visit_impl_item_fn(self, node);
    }

    fn visit_item_trait(&mut self, node: &'ast ItemTrait) {
        if !self.ships() || !matches!(node.vis, syn::Visibility::Public(_)) {
            syn::visit::visit_item_trait(self, node);
            return;
        }
        let name = node.ident.to_string();
        if node
            .supertraits
            .iter()
            .any(|bound| bound_is(bound, "Layer"))
        {
            self.layer_subtraits.push(name.clone());
        }
        let fns = node
            .items
            .iter()
            .filter_map(|item| match item {
                TraitItem::Fn(f) => Some(f.sig.ident.to_string()),
                _ => None,
            })
            .collect();
        self.trait_methods.push((name, fns));
        syn::visit::visit_item_trait(self, node);
    }

    fn visit_item_struct(&mut self, node: &'ast syn::ItemStruct) {
        if nest_rs_conformance::sources::config_namespace(&node.attrs).is_some() && self.ships() {
            self.configs.push(ConfigDecl {
                name: node.ident.to_string(),
                fields: node
                    .fields
                    .iter()
                    .filter_map(|f| f.ident.as_ref().map(ToString::to_string))
                    .collect(),
                profile_split: false,
            });
        }
        syn::visit::visit_item_struct(self, node);
    }

    /// `fn defaults()` lives in the `Config` impl beside the struct, so the two
    /// halves are stitched here rather than in a second pass.
    fn visit_item_impl(&mut self, node: &'ast syn::ItemImpl) {
        let branches = node.items.iter().any(|item| {
            let syn::ImplItem::Fn(f) = item else {
                return false;
            };
            f.sig.ident == "defaults" && spells_dev_profile(f)
        });
        if branches
            && let syn::Type::Path(p) = &*node.self_ty
            && let Some(last) = p.path.segments.last()
            && let Some(decl) = self.configs.iter_mut().find(|c| last.ident == c.name)
        {
            decl.profile_split = true;
        }
        syn::visit::visit_item_impl(self, node);
    }
}

/// Whether a supertrait bound names `name` as its last segment.
fn bound_is(bound: &syn::TypeParamBound, name: &str) -> bool {
    let syn::TypeParamBound::Trait(t) = bound else {
        return false;
    };
    t.path.segments.last().is_some_and(|s| s.ident == name)
}

/// Whether a `defaults()` body consults the profile.
fn spells_dev_profile(f: &syn::ImplItemFn) -> bool {
    use quote::ToTokens;
    f.block
        .to_token_stream()
        .to_string()
        .contains("dev_profile")
}

/// `major.minor` of the framework, from the root manifest's
/// `[workspace.package]`.
fn version_req(root: &Path) -> String {
    let manifest = read(&root.join("Cargo.toml")).expect("the repo root has a manifest");
    let doc: toml_edit::DocumentMut = manifest.parse().expect("the root manifest is valid TOML");
    let version = doc
        .get("workspace")
        .and_then(|w| w.get("package"))
        .and_then(|p| p.get("version"))
        .and_then(|v| v.as_str())
        .expect("`[workspace.package] version` is what every crate inherits");
    let (major, rest) = version
        .split_once('.')
        .expect("a workspace version is `major.minor.patch`");
    let minor = rest.split('.').next().unwrap_or_default();
    format!("{major}.{minor}")
}

/// The binding `nest-rs-opentelemetry`'s boot panic names.
///
/// Read out of the panic rather than restated: 1.3.0 corrected that message to
/// `_otel` and left the docs' canonical `main` on the old `_opentelemetry`, so
/// the reader who tripped the panic was sent to a line the example they started
/// from did not contain.
fn otel_binding(root: &Path) -> String {
    let source = root.join("crates/nest-rs-opentelemetry/src/module.rs");
    let text = read(&source).expect("nest-rs-opentelemetry declares its module");
    let marker = "Add `let ";
    let start = text
        .find(marker)
        .map(|i| i + marker.len())
        .unwrap_or_else(|| {
            panic!(
                "nest-rs-opentelemetry's boot panic no longer reads \"Add `let <binding> =\" — \
                 teach `otel_binding` the new wording, do not delete the fact"
            )
        });
    text[start..]
        .split(|c: char| !(c.is_alphanumeric() || c == '_'))
        .find(|word| !word.is_empty())
        .expect("the panic names a binding")
        .to_owned()
}

/// The keys `nest_rs_queue::envelope` seals onto the wire.
///
/// A page publishing the envelope shape teaches a third-party driver what to
/// produce, and a key the framework adds and the page omits is a driver that
/// compiles, runs, and drops it across the one hop the framework crosses as a
/// *process*.
fn envelope_keys(root: &Path) -> Vec<String> {
    let source = root.join("crates/nest-rs-queue/src/envelope.rs");
    let ast = parsed(&source).expect("the queue declares its wire envelope");
    let mut keys = BTreeSet::new();
    for item in &ast.items {
        let syn::Item::Const(c) = item else {
            continue;
        };
        if let syn::Expr::Lit(lit) = &*c.expr
            && let syn::Lit::Str(s) = &lit.lit
        {
            keys.insert(s.value());
        }
    }
    keys.into_iter().collect()
}

/// The two regions of the architecture rules the `/architecture/` page restates.
///
/// Sliced, never tokenized — the linter owns the one definition of what a role
/// token is, and it applies it to both sides. Slicing a region wrong is loud:
/// the floors in [`derive`] fail rather than publishing an empty canon that a
/// drifting page would then agree with.
fn architecture(root: &Path) -> ArchitectureFacts {
    /// The headings whose fenced block lists the reserved words. Two spellings
    /// because the rules file and the page word the section differently, and
    /// the page is free to.
    const RESERVED_SECTIONS: [&str; 2] = ["Reserved vocabulary", "What a folder may not be called"];

    let source = root.join("crates/nest-rs-cli/src/templates/architecture.md");
    let text = read(&source).expect("the CLI embeds the architecture rules");

    let role_rows = text
        .lines()
        .filter(|line| line.starts_with('|'))
        .map(str::to_owned)
        .collect();

    let mut reserved_block = String::new();
    let mut section = String::new();
    let mut inside = false;
    for line in text.lines() {
        if let Some(heading) = line.strip_prefix("## ") {
            section = heading.trim().to_owned();
            continue;
        }
        if line.starts_with("```") {
            if inside {
                break;
            }
            inside = RESERVED_SECTIONS.contains(&section.as_str());
            continue;
        }
        if inside {
            reserved_block.push_str(line);
            reserved_block.push('\n');
        }
    }

    ArchitectureFacts {
        role_rows,
        reserved_block,
    }
}

/// Every `.rs` the demo workspace holds, with the facts a fence quoting it is
/// checked against — that it exists, what it contains, and what port it pins.
fn demo_files(root: &Path) -> BTreeMap<String, DemoFile> {
    let mut out = BTreeMap::new();
    for workspace in ["demo/apps", "demo/crates"] {
        for file in files_with_extension(&root.join(workspace), "rs") {
            let Ok(text) = fs::read_to_string(&file) else {
                continue;
            };
            out.insert(
                relative(&file, root),
                DemoFile {
                    port: pinned_port(&text),
                    lines: text
                        .lines()
                        .map(str::trim)
                        .filter(|line| !line.is_empty())
                        .map(str::to_owned)
                        .collect(),
                },
            );
        }
    }
    out
}

/// The `port:` a demo file pins, or `None`.
///
/// A field initializer, so the scan is for the literal that follows the field
/// name — the same fact the linter used to read directly out of the file, and
/// the same word boundary its regex carried: without it `export:` matches and
/// the check compares a fence against a number from another line entirely.
fn pinned_port(text: &str) -> Option<u32> {
    let mut from = 0;
    while let Some(hit) = text[from..].find("port:") {
        let at = from + hit;
        let bounded = at == 0
            || !text[..at]
                .chars()
                .next_back()
                .is_some_and(|c| c.is_alphanumeric() || c == '_');
        from = at + "port:".len();
        if !bounded {
            continue;
        }
        let digits: String = text[from..]
            .trim_start()
            .chars()
            .take_while(char::is_ascii_digit)
            .collect();
        if let Ok(port) = digits.parse() {
            return Some(port);
        }
    }
    None
}
