use std::sync::Arc;

use async_graphql::dataloader::DataLoader;
use async_graphql::Result;
use nestrs_graphql::{crud, resolver};
use uuid::Uuid;

use crate::orgs::entity::{self, CreateOrgInput, Org, UpdateOrgInput};
use crate::orgs::service::OrgsService;
use crate::users::entity::User;
use crate::users::service::UsersServiceByOrg;

/// The org root + mutation surface is generated by `#[crud]` — `orgs`/`org`/
/// `create_org`/`update_org`/`delete_org`, each **delegating to `OrgsService`**
/// (the same gateway the REST controller uses, so one implementation serves both
/// surfaces). The `#[field] users` relation is hand-written: `#[crud]` does not
/// generate relations, so it stays an override the macro keeps as-is.
#[resolver]
pub struct OrgsResolver {
    #[inject]
    svc: Arc<OrgsService>,
}

#[crud(
    service = svc,
    entity = entity::Entity,
    output = Org,
    create = CreateOrgInput,
    update = UpdateOrgInput,
)]
impl OrgsResolver {
    #[field]
    async fn users(
        &self,
        parent: &Org,
        by_org: &DataLoader<UsersServiceByOrg>,
    ) -> Result<Vec<User>> {
        let id = Uuid::parse_str(&parent.id)?;
        Ok(by_org.load_one(id).await?.unwrap_or_default())
    }
}
