[package]
name = "worker"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
nest-rs.workspace = true
features.workspace = true
anyhow.workspace = true

[dev-dependencies]
tokio.workspace = true
nest-rs.workspace = true
features = { workspace = true, features = ["test-support"] }
migrations.workspace = true
sea-orm.workspace = true
uuid.workspace = true

[lints]
workspace = true
