apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "demo.configMapName" . }}
  labels:
    {{- include "demo.labels" . | nindent 4 }}
data:
  {{- include "demo.plainConfig" . | trim | nindent 2 }}
