{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "demo.secretName" . }}
  labels:
    {{- include "demo.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets }}
  {{ printf "%s_%s" $.Values.envPrefix $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
