input CreateOrg {
	name: String!
}

input CreateUser {
	email: String!
	name: String!
}

type Mutation {
	createOrg(input: CreateOrg!): Org!
	createUser(input: CreateUser!): User!
	deleteOrg(id: String!): Boolean!
	deleteUser(id: String!): Boolean!
	publishPost(id: String!): Post
	updateOrg(id: String!, input: UpdateOrg!): Org
	updateUser(id: String!, input: UpdateUser!): User
}

type Org {
	createdAt: String!
	id: String!
	name: String!
	posts(after: String, first: Int): PostConnection!
	updatedAt: String!
	users(after: String, first: Int): UserConnection!
}

"""
Information about pagination in a connection
"""
type PageInfo {
	"""
	When paginating forwards, the cursor to continue.
	"""
	endCursor: String
	"""
	When paginating forwards, are there more items?
	"""
	hasNextPage: Boolean!
	"""
	When paginating backwards, are there more items?
	"""
	hasPreviousPage: Boolean!
	"""
	When paginating backwards, the cursor to continue.
	"""
	startCursor: String
}

type Post {
	author: User
	authorId: String!
	body: String!
	createdAt: String!
	id: String!
	org: Org
	orgId: String!
	status: PostStatus!
	title: String!
	updatedAt: String!
}

type PostConnection {
	"""
	A list of edges.
	"""
	edges: [PostEdge!]!
	"""
	A list of nodes.
	"""
	nodes: [Post!]!
	"""
	Information to aid in pagination.
	"""
	pageInfo: PageInfo!
}

"""
An edge in a connection.
"""
type PostEdge {
	"""
	A cursor for use in pagination
	"""
	cursor: String!
	"""
	The item at the end of the edge
	"""
	node: Post!
}

enum PostStatus {
	DRAFT
	PUBLISHED
}

type Query {
	org(id: String!): Org
	orgs(after: String, first: Int): [Org!]!
	post(id: String!): Post
	posts(after: String, first: Int): [Post!]!
	user(id: String!): User
	users(after: String, first: Int): [User!]!
}

type Subscription {
	postPublished: Post!
}

input UpdateOrg {
	name: String!
}

input UpdateUser {
	email: String!
	name: String!
}

type User {
	createdAt: String!
	email: String!
	id: String!
	name: String!
	org: Org
	orgId: String!
	posts(after: String, first: Int): PostConnection!
	updatedAt: String!
}

type UserConnection {
	"""
	A list of edges.
	"""
	edges: [UserEdge!]!
	"""
	A list of nodes.
	"""
	nodes: [User!]!
	"""
	Information to aid in pagination.
	"""
	pageInfo: PageInfo!
}

"""
An edge in a connection.
"""
type UserEdge {
	"""
	A cursor for use in pagination
	"""
	cursor: String!
	"""
	The item at the end of the edge
	"""
	node: User!
}

"""
Directs the executor to include this field or fragment only when the `if` argument is true.
"""
directive @include(if: Boolean!) on FIELD | FRAGMENT_SPREAD | INLINE_FRAGMENT
"""
Directs the executor to skip this field or fragment when the `if` argument is true.
"""
directive @skip(if: Boolean!) on FIELD | FRAGMENT_SPREAD | INLINE_FRAGMENT
schema {
	query: Query
	mutation: Mutation
	subscription: Subscription
}
