//! Cross-entity bridges that let one `#[expose]` macro emit a field resolver
//! pointing at another entity's loader **without knowing its service name**.
//!
//! Each `#[expose]` emits an impl of [`PkLoadable`] on its entity (Phase 1)
//! and, when relevant, of [`RelatedTo<Parent>`] (Phase 2 / `HasMany`). A field
//! resolver on the `belongs_to` side only needs the target entity's path —
//! the loader struct it must pull from the request context is reached via
//! `<TargetEntity as PkLoadable>::Loader`, and the GraphQL output type via
//! `<TargetEntity as PkLoadable>::Wire`.

use async_graphql::OutputType;

/// "This entity exposes a primary-key loader and a wire DTO." Implemented
/// automatically by `#[expose]` on every entity that declares a `service = …`.
///
/// - `Loader` is the struct generated by `#[dataloader]` on the entity's
///   `by_id` method — typically named `<Service>ById`.
/// - `Wire` is the GraphQL output type emitted by `#[expose(name = "…")]`.
pub trait PkLoadable {
    type Loader: ::core::marker::Send + ::core::marker::Sync + 'static;
    type Wire: OutputType + ::core::marker::Send + ::core::marker::Sync + 'static;
}

/// "This entity is the child of `Parent`, fetched in batches by its
/// foreign-key column." Phase 2 — populated by `#[expose]` on the entity
/// owning the FK.
pub trait RelatedTo<Parent: ?Sized> {
    type Loader: ::core::marker::Send + ::core::marker::Sync + 'static;
    type Wire: OutputType + ::core::marker::Send + ::core::marker::Sync + 'static;
}
